[package]
name = "kv_store_ninja"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
skiplist = "0.3"
clap = { version = "4.0", features = ["derive"] }